#ifndef __GUIMyFrame__
#define __GUIMyFrame__

/**
@file
Subclass of MyFrame2, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

/** Implementing MyFrame2 */
class GUIMyFrame : public MyFrame2
{
protected:
	// Handlers for MyFrame2 events.
	void onUpdateUI(wxUpdateUIEvent& event);
	void saveToFileClick(wxCommandEvent& event);
	void on_addSource1Click(wxCommandEvent& event);
	void on_addSource2Click(wxCommandEvent& event);
	void onScrollX(wxScrollEvent& event);
	void onScrollY(wxScrollEvent& event);
	void onScrollZ(wxScrollEvent& event);
	void nextClick(wxCommandEvent& event);
	void prevClick(wxCommandEvent& event);
	void copyClick(wxCommandEvent& event);
	void startClick(wxCommandEvent& event);
	void resetClick(wxCommandEvent& event);
public:
	/** Constructor */
	GUIMyFrame(wxWindow* parent);
	//// end generated class members

};

#endif // __GUIMyFrame__
