#ifndef __GUIMyFrame__
#define __GUIMyFrame__

//// end generated include
#include <wx/wx.h>
#include <wx/wxprec.h>
#include <wx/dcbuffer.h>
#include <wx/window.h>
#include <wx/scrolbar.h>
#include <wx/clipbrd.h>
#include <wx/printdlg.h>
#include <wx/mousestate.h>
#include <wx/dcclient.h>

#include <vector>
#include <array>
#include <string>
#include <exception>

#include "myMatrix.h"
#include "CustomDialog.h"
#include "transformations.h"

/**
@file
Subclass of MyFrame2, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

/** Implementing MyFrame2 */
class GUIMyFrame : public MyFrame2
{
protected:
	// Handlers for MyFrame2 events.
	void onUpdateUI(wxUpdateUIEvent& event);
	void saveToFileClick(wxCommandEvent& event);
	void on_addSource1Click(wxCommandEvent& event);
	void on_addSource2Click(wxCommandEvent& event);
	void onScrollX(wxScrollEvent& event);
	void onScrollY(wxScrollEvent& event);
	void onScrollZ(wxScrollEvent& event);
	void nextClick(wxCommandEvent& event);
	void prevClick(wxCommandEvent& event);
	void copyClick(wxCommandEvent& event);
	void startClick(wxCommandEvent& event);
	void resetClick(wxCommandEvent& event);

public:
	GUIMyFrame(wxWindow* parent);

	void Paint();
	void Draw();
	double measureDistance(double x1, double y1, double x2, double y2);

	wxImage interferenceImage;
	wxBitmap myBuffer;
	wxClientDC myClient;
	wxTimer timer;
	myMatrix transformMatrix;
	unsigned seconds = 0;
	int duration = 10;
	double time = 0.0;
	double scaleX, scaleY;
	unsigned pointsX, pointsY;

	std::vector<std::vector<wxPoint>> points1;
	std::vector<std::vector<wxPoint>> drawPoints1;
	std::vector<std::vector<double>> points1Distance;
	std::vector<double> points1Amplitude;
	std::vector<double> points1Frequency;
	unsigned counter1 = 0;
	bool flag1 = true;
	
	std::vector<std::vector<wxPoint>> points2;
	std::vector<std::vector<wxPoint>> drawPoints2;
	std::vector<std::vector<double>> points2Distance;
	std::vector<double> points2Amplitude;
	std::vector<double> points2Frequency;
	unsigned counter2 = 0;
	bool flag2 = true;
};

#endif // __GUIMyFrame__
