#ifndef __GUIMyFrame__
#define __GUIMyFrame__

//// end generated include
#include <wx/wx.h>
#include <wx/wxprec.h>
#include <wx/dcbuffer.h>
#include <wx/window.h>
#include <wx/scrolbar.h>
#include <wx/clipbrd.h>
#include <wx/printdlg.h>
#include <wx/mousestate.h>
#include <wx/dcclient.h>

#include <vector>
#include <array>
#include <string>
#include <exception>

#include "myMatrix.h"
#include "MyDialog.h"
#include "transformations.h"

/**
@file
Subclass of MyFrame2, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

/** Implementing MyFrame2 */
class GUIMyFrame : public MyFrame2
{
protected:
	// Handlers for MyFrame2 events.
	void onUpdateUI(wxUpdateUIEvent& event);
	void saveToFileClick(wxCommandEvent& event);
	void on_addSource1Click(wxCommandEvent& event);
	void on_addSource2Click(wxCommandEvent& event);
	void onScrollX(wxScrollEvent& event);
	void onScrollY(wxScrollEvent& event);
	void onScrollZ(wxScrollEvent& event);
	void nextClick(wxCommandEvent& event);
	void prevClick(wxCommandEvent& event);
	void copyClick(wxCommandEvent& event);
	void startClick(wxCommandEvent& event);
	void resetClick(wxCommandEvent& event);

public:
	GUIMyFrame(wxWindow* parent);

	void Paint();
	void scroll();
	void initializeVec(unsigned, unsigned, double, double);
	double measureDistance(const double x1, const  double y1, const  double x2, const  double y2);
	void addSource(std::vector<std::vector<wxPoint>>& points, std::vector<std::vector<double>>& pointsDistance,
		double& pointsAmplitude, double& pointsFrequency, bool& flag);
	void clearDistance(std::vector<std::vector<wxPoint>>& points, std::vector<std::vector<double>>& pointsDistance, double&, double&);

	wxImage interferenceImage;
	wxBitmap myBuffer;
	wxClientDC myClient;
	wxTimer timer;
	myMatrix transformMatrix;
	unsigned seconds = 0;
	int duration = 6;
	double time = 0.0;
	double scaleX, scaleY;
	unsigned pointsX, pointsY;

	std::vector<std::vector<wxPoint>> points;
	std::vector<std::vector<wxPoint>> drawPoints;
	std::vector<std::vector<double>> points1Distance;
	double points1Amplitude;
	double points1Frequency;
	bool flag1 = true;

	std::vector<std::vector<double>> points2Distance;
	double points2Amplitude;
	double points2Frequency;
	bool flag2 = true;
	
};



#endif // __GUIMyFrame__
